---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# lterpalettefinder

<!-- badges: start -->
<!-- badges: end -->

The goal of `lterpalettefinder` is to provide high quality color palettes derived from photos at LTER sites. This allows users to create beautiful graphics that have close visual ties to photos from the places where data were collected. This package also allows users to generate their own palettes from any photo (.PNG only) if the current palettes in the function do not meet their needs.

## Installation

You can install the development version of `lterpalettefinder` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("njlyon0/lterpalettefinder")
```

## Functions

This package currently includes two functions

- `palette_finder()` allows you to specify criteria for your desired palette and returns the palette(s) that we have already created that meet those criteria
- `palette_extractor()` allows you to extract hexadecimal codes from a picture of your choosing (only PNG format is currently supported)

## Palette Examples

This part of the README is in development so stay tuned!
